### ISSUE TITLE
O resultado(Pasta Estados) deve ser gravado no seguinte repositorio: Arquivo

### ISSUE THREAD

**Issue by eldersantos** [CovidZero/Crawler#2]
O resultado da excução do crawler deve ser gravado no repositório https://github.com/CovidZeroNews/Arquivo

**Comment by eldersantos** [comment]
@Suburbanno Acho que vc já fez essa parte, mas apenas para termos a lista de atividades

**Comment by Suburbanno** [comment]
https://github.com/CovidZeroNews/Crawler/issues/8

**Comment by jrick166fiap** [comment]
sim claro.
